-- Allow CTE (WITH ... AS ...) syntax in execute_readonly_query.
--
-- CTEs are valid read-only SQL. The previous check rejected any query that
-- did not begin with SELECT, which incorrectly blocked WITH ... SELECT ...
-- queries generated by the SQL analyst for time-series YoY calculations.
-- Updating the check to also allow queries that begin with WITH.

CREATE OR REPLACE FUNCTION public.execute_readonly_query(query_text TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result JSONB;
  upper_query TEXT;
BEGIN
  upper_query := UPPER(TRIM(query_text));

  -- Allow SELECT queries and CTE (WITH ... AS ... SELECT) queries only
  IF NOT (upper_query LIKE 'SELECT%' OR upper_query LIKE 'WITH%') THEN
    RAISE EXCEPTION 'Only SELECT queries are allowed';
  END IF;

  -- Block dangerous keywords
  IF upper_query ~ '(DELETE|DROP|INSERT|UPDATE|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|EXECUTE)' THEN
    RAISE EXCEPTION 'Forbidden SQL operation detected';
  END IF;

  -- Wrap in a 500-row cap so a single call can never dump the full table
  EXECUTE format(
    'SELECT jsonb_agg(row_to_json(t)) FROM (SELECT * FROM (%s) raw LIMIT 500) t',
    query_text
  ) INTO result;

  RETURN COALESCE(result, '[]'::jsonb);
END;
$$;

-- Ensure grants remain correct after the OR REPLACE
REVOKE EXECUTE ON FUNCTION public.execute_readonly_query(TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.execute_readonly_query(TEXT) FROM anon;
REVOKE EXECUTE ON FUNCTION public.execute_readonly_query(TEXT) FROM authenticated;
GRANT  EXECUTE ON FUNCTION public.execute_readonly_query(TEXT) TO service_role;
